name: Test
on: push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v2.5.1
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm test
